// Code generated by schema-generate. DO NOT EDIT.

package taskset

import (
    "bytes"
    "encoding/json"
    "fmt"
    "errors"
)

// AwsVpcConfiguration The VPC subnets and security groups associated with a task. All specified subnets and security groups must be from the same VPC.
type AwsVpcConfiguration struct {

  // Whether the task's elastic network interface receives a public IP address. The default value is DISABLED.
  AssignPublicIp string `json:"AssignPublicIp,omitempty"`

  // The security groups associated with the task or service. If you do not specify a security group, the default security group for the VPC is used. There is a limit of 5 security groups that can be specified per AwsVpcConfiguration.
  SecurityGroups []string `json:"SecurityGroups,omitempty"`

  // The subnets associated with the task or service. There is a limit of 16 subnets that can be specified per AwsVpcConfiguration.
  Subnets []string `json:"Subnets"`
}

// LoadBalancer A load balancer object representing the load balancer to use with the task set. The supported load balancer types are either an Application Load Balancer or a Network Load Balancer. 
type LoadBalancer struct {

  // The name of the container (as it appears in a container definition) to associate with the load balancer.
  ContainerName string `json:"ContainerName,omitempty"`

  // The port on the container to associate with the load balancer. This port must correspond to a containerPort in the task definition the tasks in the service are using. For tasks that use the EC2 launch type, the container instance they are launched on must allow ingress traffic on the hostPort of the port mapping.
  ContainerPort int `json:"ContainerPort,omitempty"`

  // The name of the load balancer to associate with the Amazon ECS service or task set. A load balancer name is only specified when using a Classic Load Balancer. If you are using an Application Load Balancer or a Network Load Balancer this should be omitted.
  LoadBalancerName string `json:"LoadBalancerName,omitempty"`

  // The full Amazon Resource Name (ARN) of the Elastic Load Balancing target group or groups associated with a service or task set. A target group ARN is only specified when using an Application Load Balancer or Network Load Balancer. If you are using a Classic Load Balancer this should be omitted. For services using the ECS deployment controller, you can specify one or multiple target groups. For more information, see https://docs.aws.amazon.com/AmazonECS/latest/developerguide/register-multiple-targetgroups.html in the Amazon Elastic Container Service Developer Guide. For services using the CODE_DEPLOY deployment controller, you are required to define two target groups for the load balancer. For more information, see https://docs.aws.amazon.com/AmazonECS/latest/developerguide/deployment-type-bluegreen.html in the Amazon Elastic Container Service Developer Guide. If your service's task definition uses the awsvpc network mode (which is required for the Fargate launch type), you must choose ip as the target type, not instance, when creating your target groups because tasks that use the awsvpc network mode are associated with an elastic network interface, not an Amazon EC2 instance.
  TargetGroupArn string `json:"TargetGroupArn,omitempty"`
}

// NetworkConfiguration An object representing the network configuration for a task or service.
type NetworkConfiguration struct {
  AwsVpcConfiguration *AwsVpcConfiguration `json:"AwsVpcConfiguration,omitempty"`
}

// Resource Create a task set in the specified cluster and service. This is used when a service uses the EXTERNAL deployment controller type. For more information, see https://docs.aws.amazon.com/AmazonECS/latest/developerguide/deployment-types.htmlin the Amazon Elastic Container Service Developer Guide.
type Resource struct {

  // The short name or full Amazon Resource Name (ARN) of the cluster that hosts the service to create the task set in.
  Cluster string `json:"Cluster"`

  // An optional non-unique tag that identifies this task set in external systems. If the task set is associated with a service discovery registry, the tasks in this task set will have the ECS_TASK_SET_EXTERNAL_ID AWS Cloud Map attribute set to the provided value. 
  ExternalId string `json:"ExternalId,omitempty"`

  // The ID of the task set.
  Id string `json:"Id,omitempty"`

  // The launch type that new tasks in the task set will use. For more information, see https://docs.aws.amazon.com/AmazonECS/latest/developerguide/launch_types.html in the Amazon Elastic Container Service Developer Guide. 
  LaunchType string `json:"LaunchType,omitempty"`
  LoadBalancers []*LoadBalancer `json:"LoadBalancers,omitempty"`
  NetworkConfiguration *NetworkConfiguration `json:"NetworkConfiguration,omitempty"`

  // The platform version that the tasks in the task set should use. A platform version is specified only for tasks using the Fargate launch type. If one isn't specified, the LATEST platform version is used by default.
  PlatformVersion string `json:"PlatformVersion,omitempty"`

  // A floating-point percentage of the desired number of tasks to place and keep running in the task set.
  Scale *Scale `json:"Scale,omitempty"`

  // The short name or full Amazon Resource Name (ARN) of the service to create the task set in.
  Service string `json:"Service"`

  // The details of the service discovery registries to assign to this task set. For more information, see https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-discovery.html.
  ServiceRegistries []*ServiceRegistry `json:"ServiceRegistries,omitempty"`

  // The short name or full Amazon Resource Name (ARN) of the task definition for the tasks in the task set to use.
  TaskDefinition string `json:"TaskDefinition"`
}

// Scale 
type Scale struct {

  // The unit of measure for the scale value.
  Unit string `json:"Unit,omitempty"`

  // The value, specified as a percent total of a service's desiredCount, to scale the task set. Accepted values are numbers between 0 and 100.
  Value float64 `json:"Value,omitempty"`
}

// ServiceRegistry 
type ServiceRegistry struct {

  // The container name value, already specified in the task definition, to be used for your service discovery service. If the task definition that your service task specifies uses the bridge or host network mode, you must specify a containerName and containerPort combination from the task definition. If the task definition that your service task specifies uses the awsvpc network mode and a type SRV DNS record is used, you must specify either a containerName and containerPort combination or a port value, but not both.
  ContainerName string `json:"ContainerName,omitempty"`

  // The port value, already specified in the task definition, to be used for your service discovery service. If the task definition your service task specifies uses the bridge or host network mode, you must specify a containerName and containerPort combination from the task definition. If the task definition your service task specifies uses the awsvpc network mode and a type SRV DNS record is used, you must specify either a containerName and containerPort combination or a port value, but not both.
  ContainerPort int `json:"ContainerPort,omitempty"`

  // The port value used if your service discovery service specified an SRV record. This field may be used if both the awsvpc network mode and SRV records are used.
  Port int `json:"Port,omitempty"`

  // The Amazon Resource Name (ARN) of the service registry. The currently supported service registry is AWS Cloud Map. For more information, see https://docs.aws.amazon.com/cloud-map/latest/api/API_CreateService.html
  RegistryArn string `json:"RegistryArn,omitempty"`
}

func (strct *AwsVpcConfiguration) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // Marshal the "AssignPublicIp" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"AssignPublicIp\": ")
	if tmp, err := json.Marshal(strct.AssignPublicIp); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "SecurityGroups" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"SecurityGroups\": ")
	if tmp, err := json.Marshal(strct.SecurityGroups); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "Subnets" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "Subnets" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"Subnets\": ")
	if tmp, err := json.Marshal(strct.Subnets); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *AwsVpcConfiguration) UnmarshalJSON(b []byte) error {
    SubnetsReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "AssignPublicIp":
            if err := json.Unmarshal([]byte(v), &strct.AssignPublicIp); err != nil {
                return err
             }
        case "SecurityGroups":
            if err := json.Unmarshal([]byte(v), &strct.SecurityGroups); err != nil {
                return err
             }
        case "Subnets":
            if err := json.Unmarshal([]byte(v), &strct.Subnets); err != nil {
                return err
             }
            SubnetsReceived = true
        default:
            return fmt.Errorf("additional property not allowed: \"" + k + "\"")
        }
    }
    // check if Subnets (a required property) was received
    if !SubnetsReceived {
        return errors.New("\"Subnets\" is required but was not present")
    }
    return nil
}

func (strct *LoadBalancer) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // Marshal the "ContainerName" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"ContainerName\": ")
	if tmp, err := json.Marshal(strct.ContainerName); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "ContainerPort" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"ContainerPort\": ")
	if tmp, err := json.Marshal(strct.ContainerPort); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "LoadBalancerName" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"LoadBalancerName\": ")
	if tmp, err := json.Marshal(strct.LoadBalancerName); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "TargetGroupArn" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"TargetGroupArn\": ")
	if tmp, err := json.Marshal(strct.TargetGroupArn); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *LoadBalancer) UnmarshalJSON(b []byte) error {
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "ContainerName":
            if err := json.Unmarshal([]byte(v), &strct.ContainerName); err != nil {
                return err
             }
        case "ContainerPort":
            if err := json.Unmarshal([]byte(v), &strct.ContainerPort); err != nil {
                return err
             }
        case "LoadBalancerName":
            if err := json.Unmarshal([]byte(v), &strct.LoadBalancerName); err != nil {
                return err
             }
        case "TargetGroupArn":
            if err := json.Unmarshal([]byte(v), &strct.TargetGroupArn); err != nil {
                return err
             }
        default:
            return fmt.Errorf("additional property not allowed: \"" + k + "\"")
        }
    }
    return nil
}

func (strct *NetworkConfiguration) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // Marshal the "AwsVpcConfiguration" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"AwsVpcConfiguration\": ")
	if tmp, err := json.Marshal(strct.AwsVpcConfiguration); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *NetworkConfiguration) UnmarshalJSON(b []byte) error {
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "AwsVpcConfiguration":
            if err := json.Unmarshal([]byte(v), &strct.AwsVpcConfiguration); err != nil {
                return err
             }
        default:
            return fmt.Errorf("additional property not allowed: \"" + k + "\"")
        }
    }
    return nil
}

func (strct *Resource) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // "Cluster" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "Cluster" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"Cluster\": ")
	if tmp, err := json.Marshal(strct.Cluster); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "ExternalId" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"ExternalId\": ")
	if tmp, err := json.Marshal(strct.ExternalId); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "Id" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"Id\": ")
	if tmp, err := json.Marshal(strct.Id); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "LaunchType" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"LaunchType\": ")
	if tmp, err := json.Marshal(strct.LaunchType); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "LoadBalancers" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"LoadBalancers\": ")
	if tmp, err := json.Marshal(strct.LoadBalancers); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "NetworkConfiguration" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"NetworkConfiguration\": ")
	if tmp, err := json.Marshal(strct.NetworkConfiguration); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "PlatformVersion" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"PlatformVersion\": ")
	if tmp, err := json.Marshal(strct.PlatformVersion); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "Scale" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"Scale\": ")
	if tmp, err := json.Marshal(strct.Scale); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "Service" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "Service" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"Service\": ")
	if tmp, err := json.Marshal(strct.Service); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "ServiceRegistries" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"ServiceRegistries\": ")
	if tmp, err := json.Marshal(strct.ServiceRegistries); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "TaskDefinition" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "TaskDefinition" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"TaskDefinition\": ")
	if tmp, err := json.Marshal(strct.TaskDefinition); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *Resource) UnmarshalJSON(b []byte) error {
    ClusterReceived := false
    ServiceReceived := false
    TaskDefinitionReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "Cluster":
            if err := json.Unmarshal([]byte(v), &strct.Cluster); err != nil {
                return err
             }
            ClusterReceived = true
        case "ExternalId":
            if err := json.Unmarshal([]byte(v), &strct.ExternalId); err != nil {
                return err
             }
        case "Id":
            if err := json.Unmarshal([]byte(v), &strct.Id); err != nil {
                return err
             }
        case "LaunchType":
            if err := json.Unmarshal([]byte(v), &strct.LaunchType); err != nil {
                return err
             }
        case "LoadBalancers":
            if err := json.Unmarshal([]byte(v), &strct.LoadBalancers); err != nil {
                return err
             }
        case "NetworkConfiguration":
            if err := json.Unmarshal([]byte(v), &strct.NetworkConfiguration); err != nil {
                return err
             }
        case "PlatformVersion":
            if err := json.Unmarshal([]byte(v), &strct.PlatformVersion); err != nil {
                return err
             }
        case "Scale":
            if err := json.Unmarshal([]byte(v), &strct.Scale); err != nil {
                return err
             }
        case "Service":
            if err := json.Unmarshal([]byte(v), &strct.Service); err != nil {
                return err
             }
            ServiceReceived = true
        case "ServiceRegistries":
            if err := json.Unmarshal([]byte(v), &strct.ServiceRegistries); err != nil {
                return err
             }
        case "TaskDefinition":
            if err := json.Unmarshal([]byte(v), &strct.TaskDefinition); err != nil {
                return err
             }
            TaskDefinitionReceived = true
        default:
            return fmt.Errorf("additional property not allowed: \"" + k + "\"")
        }
    }
    // check if Cluster (a required property) was received
    if !ClusterReceived {
        return errors.New("\"Cluster\" is required but was not present")
    }
    // check if Service (a required property) was received
    if !ServiceReceived {
        return errors.New("\"Service\" is required but was not present")
    }
    // check if TaskDefinition (a required property) was received
    if !TaskDefinitionReceived {
        return errors.New("\"TaskDefinition\" is required but was not present")
    }
    return nil
}

func (strct *Scale) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // Marshal the "Unit" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"Unit\": ")
	if tmp, err := json.Marshal(strct.Unit); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "Value" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"Value\": ")
	if tmp, err := json.Marshal(strct.Value); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *Scale) UnmarshalJSON(b []byte) error {
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "Unit":
            if err := json.Unmarshal([]byte(v), &strct.Unit); err != nil {
                return err
             }
        case "Value":
            if err := json.Unmarshal([]byte(v), &strct.Value); err != nil {
                return err
             }
        default:
            return fmt.Errorf("additional property not allowed: \"" + k + "\"")
        }
    }
    return nil
}

func (strct *ServiceRegistry) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // Marshal the "ContainerName" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"ContainerName\": ")
	if tmp, err := json.Marshal(strct.ContainerName); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "ContainerPort" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"ContainerPort\": ")
	if tmp, err := json.Marshal(strct.ContainerPort); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "Port" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"Port\": ")
	if tmp, err := json.Marshal(strct.Port); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "RegistryArn" field
    if comma { 
        buf.WriteString(",") 
    }
    buf.WriteString("\"RegistryArn\": ")
	if tmp, err := json.Marshal(strct.RegistryArn); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *ServiceRegistry) UnmarshalJSON(b []byte) error {
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "ContainerName":
            if err := json.Unmarshal([]byte(v), &strct.ContainerName); err != nil {
                return err
             }
        case "ContainerPort":
            if err := json.Unmarshal([]byte(v), &strct.ContainerPort); err != nil {
                return err
             }
        case "Port":
            if err := json.Unmarshal([]byte(v), &strct.Port); err != nil {
                return err
             }
        case "RegistryArn":
            if err := json.Unmarshal([]byte(v), &strct.RegistryArn); err != nil {
                return err
             }
        default:
            return fmt.Errorf("additional property not allowed: \"" + k + "\"")
        }
    }
    return nil
}
